sudo: required
language: node_js
node_js:
  stable
services:
  - docker
branches:
  only:
  - master
  - /^greenkeeper/.*$/
before_install:
 - docker build -t minimalcss:tests .
script:
  - docker container run -it minimalcss:tests yarn test
  - docker container run -it minimalcss:tests yarn lintcheck
  - docker container run -it minimalcss:tests
